import turtle
c1 = str(input("Type a python color for the background: "))
c2 = str(input("Type a python color for the turtle: "))
c3 = str(input("Type a python color for the shape: "))
t = turtle.Turtle()
t.speed(0)
t.pensize(6)
t.pencolor(c2)
turtle.bgcolor(c1)
turtle.pensize(6)
turtle.pencolor(c2)
turtle.speed(0)
turtle.setup(1000, 600)
turtle.hideturtle()
#########basecase############
def hexagon():
        t.fillcolor(c3)
        t.begin_fill()
        for i in range(7):
            t.forward(50)
            t.left(60)
        t.end_fill()
hexagon()

def square():
        t.fillcolor(c3)
        t.begin_fill()
        for a in range(2):
            for i in range(4):
                t.forward(50)
                t.right(90)
            t.left(210)
        t.left(60)
        t.forward(50)
        t.left(30)
        for a in range(4):
            for i in range(7):
                t.forward(50)
                t.right(90)
            t.left(210)
        t.end_fill()
square()
########creates a loop for the middle########
def middle():
    for a in range(5):
        t.left(60)
        t.forward(50)
        t.right(30)
        hexagon()
        square()
middle()
######for the lower right from middle########
for a in range(2):
    t.forward(50)
    t.right(90)
    hexagon()
    square()
for a in range(9):
    t.left(150)
    t.forward(50)
    t.left(60)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.right(90)
    hexagon()
    square()

t.forward(50)
t.right(90)
hexagon()
square()
#########finishing the middle##########
for i in range(4):
    t.left(60)
    t.forward(50)
    t.left(60)
    t.right(90)
    hexagon()
    square()
    t.left(60)
    t.forward(50)
    t.right(30)
    hexagon()
    square()
    
turtle.pu()
turtle.left(210)
turtle.fd(600)
turtle.right(90)
turtle.fillcolor(c3)
turtle.begin_fill()
for i in range(6):
        turtle.forward(50)
        turtle.left(60)
turtle.end_fill()
#####creates the 3rd row from middle#####
t.left(150)
t.forward(50)
t.left(60)
t.forward(50)
t.right(30)
t.forward(50)
t.left(90)
t.forward(50)
t.right(60)
##basecase2 for going in the reverse direction##
def hexagon2():
        t.fillcolor(c3)
        t.begin_fill()
        for i in range(7):
                t.forward(50)
                t.right(60)
        t.end_fill()
hexagon2()
def square2():
    t.fillcolor(c3)
    t.begin_fill()    
    for a in range(2):
        for i in range(4):
            t.forward(50)
            t.left(90)
        t.right(210)
    t.right(60)
    t.forward(50)
    t.right(30)
    for a in range(4):
        for i in range(7):
            t.forward(50)
            t.left(90)
        t.right(210)
    t.end_fill()
square2()
###############Adjustments###############
t.forward(50)
t.right(90)
t.backward(50)
t.left(120)
hexagon2()
square2()
for a in range(8):
    t.right(60)
    t.forward(50)
    t.left(30)
    hexagon2()
    square2()

#########finishes the edge##############
####heads upwards to start a new row####
t.forward(50)
t.left(90)
hexagon2()
square2()
t.forward(50)
t.right(30)
t.fillcolor(c3)
t.begin_fill()
for i in range(4):
            t.forward(50)
            t.right(90)
t.end_fill()
t.left(120)
t.forward(50)
t.left(30)
t.forward(50)
t.right(90)
for i in range(3):
    t.forward(50)
    t.left(60)
t.right(150)
t.forward(50)
t.right(90)
hexagon()
square()
for i in range(7):
    t.left(60)
    t.forward(50)
    t.right(30)
    hexagon()
    square()
t.right(90)
for i in range(2):
        t.forward(50)
        t.right(60)
        t.forward(50)
        t.left(30)
        t.forward(50)
        t.left(30)
t.right(120)
t.forward(50)
t.right(90)
t.forward(50)
t.left(120)
t.forward(50)
t.left(30)
hexagon2()
square2()
##########completes the 3rd row up############
for i in range(5):
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.right(60)
        t.forward(50)
        t.right(60)
        hexagon2()
        square2()
t.right(150)
t.forward(50)
t.left(30)
t.forward(50)
t.right(90)
hexagon()
square()
for i in range(3):
        t.left(60)
        t.forward(50)
        t.right(30)
        hexagon()
        square()
t.right(150)
t.pu()
t.fd(237)
t.left(60)
t.forward(50)
t.right(60)
t.pd()
hexagon2()
square2()
t.forward(50)
t.left(90)
t.forward(50)
t.right(60)
t.forward(50)
t.right(60)
hexagon2()
square2()

#######home function for easier transition########
def home():
        t.pu()
        t.home()
        t.right(90)
        t.forward(138)
        t.pd()
        for i in range(2):
                t.right(60)
                t.forward(50)
                t.left(30)
                t.forward(50)
        t.left(30)
        t.forward(50)
        t.right(60)
        t.forward(50)
home()
#####more ajustments for a new row#####
t.left(90)
t.forward(50)
t.right(30)
hexagon()
square()
t.pu()
home()

t.bk(50)
t.left(90)
t.forward(50)
t.left(30)
t.forward(50)
t.left(30)
middle()
#####to repeat the row on the bottom####
def rep():
    for a in range(3):
        t.left(60)
        t.forward(50)
        t.right(30)
        hexagon()
        square()
rep()
home()
#####even more adjustments for the row that is more obscure####
t.bk(50)
t.left(90)
t.forward(50)
t.left(120)
t.forward(50)

t.right(90)
t.forward(50)
t.left(60)
t.forward(50)
t.right(30)
t.forward(50)
t.left(90)
hexagon2()
square2()

t.right(150)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
hexagon2()
square2()

for i in range(5):
        t.left(90)
        for i in range(4):
                t.forward(50)
                t.left(60)
        t.right(90)
        t.fd(50)
        t.left(90)
        hexagon2()
        square2()
        
t.left(90)
t.fd(50)
t.right(30)
t.forward(50)
t.right(30)
t.forward(50)
t.left(90)
t.pu()
t.fd(340)
t.right(90)
t.fd(300)
t.pd()
hexagon()
square()
###completing the edge rows#####
def edge():
        t.right(90)
        t.forward(50)
        t.right(60)
        t.forward(50)
        t.left(30)
        t.forward(50)
        t.left(30)
        t.forward(50)
        t.right(60)
        t.forward(50)
        t.left(180)
        hexagon()
        square()
for i in range(4):
        edge()
t.left(120)
t.pu()
t.fd(230)
t.right(90)
t.fd(165)
t.pd()
hexagon()
square()
for i in range(2):
        edge()

t.left(150)
t.fd(50)
t.right(30)
t.fd(50)
t.left(90)
hexagon2()
square2()
